### ISSUE TITLE
tox uses wrong Python interpreter locally

### ISSUE THREAD

**Issue by pohlt** [pdm-project/tox-pdm#3]
When I do a `pdm run tox -e py38` locally (where I have a python2 and python3.8 installed), tox tries to use python2 to setup the virtualenv:

``` bash
action: py38, msg: installpkg
cwd: /home/tom/proj/assertion
cmd: /usr/bin/python -m pip install --no-deps -U .tox/.tmp/package/1/assertion-0.0.1.tar.gz
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tom/proj/assertion/__pypackages__/3.8/lib/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/tom/proj/assertion/__pypackages__/3.8/lib/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

On GitLab, where I use dedicated Python containers, everything works nicely.

I guess the tox-pdm plugin is supposed to select the correct Python version, right?

**Comment by frostming** [comment]
Can you provide the `tox.ini` file content?

**Comment by pohlt** [comment]
Here are the vital parts (I guess):
```[tox]
envlist = format,mypy,pep8,py37,py38,py39,coverage

[testenv]
sections = test
commands =
    pytest tests/

...
```
I also tried to set `basepython`, but no luck so far.

**Comment by frostming** [comment]
Fixed on 0.2.0

**Comment by pohlt** [comment]
Tried it with 0.2.0 and I still see the same issue.
Never mind, I already switched to nox (thanks for your hint) and it feels so much better.
